capstone project - Budget app
looh16/Budget_app pull request #1
Opened 2022-12-01 07:53 UTC by looh16

**For this project, functionalities were implemented to allow the user:**

1. Register and log in, so that the data is private to them.
2. Introduce new transactions associated with a category.
3. See the money spent on each category.

**Tests were implemented for:**

1. Views
2. Models

[Link Demo](https://www.loom.com/share/dc7cc6dda3fb44b48a57a7894c9ccca3)

2022-12-01 08:06 UTC, thecodechaser commented
@looh16 Please check my message on slack

2022-12-01 09:49 UTC, thecodechaser commented
@looh16 Please check slack

2022-12-01 10:02 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @looh16👋, 

### You are doing a marvelous job on the RoR capstone project and this is one of the best projects I have seen so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![image](https://user-images.githubusercontent.com/83803414/205005286-07b6bc6f-0aea-415c-9091-f432383db97a.png)

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️
- All tests are passed. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️

- [ ] Please make sure the project is deployed and accessible online as requested in the project requirements.

- [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-01 10:02 UTC, thecodechaser commented on app/views/groups/new.html.erb
> +</div>
- [ ] Please make sure on `add new category` page, There's a button to go back to the homepage(category page) as requested in the project requirements.
   ![image](https://user-images.githubusercontent.com/83803414/205003255-22d26289-58e0-4f82-9ae7-a1d8917cb8e9.png)


![image](https://user-images.githubusercontent.com/83803414/205003147-89f19d68-fea7-4196-87e6-52c359ea6232.png)

2022-12-01 10:02 UTC, thecodechaser commented on app/views/entities/index.html.erb
> +</div>
- [ ] Please make sure on the `transaction` page, Users are able to see the total amount(Sum of all transaction) in that category as requested in the project requirements.
    ![image](https://user-images.githubusercontent.com/83803414/205004301-c1928769-1940-4f56-a92b-018f3c3f2b3e.png)

![image](https://user-images.githubusercontent.com/83803414/205004519-aad15f92-5a55-4faa-a283-0628ddebb6e8.png)

2022-12-02 09:23 UTC, looh16 commented
![heroku](https://user-images.githubusercontent.com/21173712/205259501-47df1ce1-5fbd-4584-90c4-cba557436205.png)

I have an error after deploying, as shown in the image, that's why I couldn't insert the application link in the readme file, I'm trying to solve the error and then I'll insert it in the readme file

2022-12-02 09:29 UTC, julie-ify approved these changes
Hi @looh16,

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 09:32 UTC, looh16 commented
Thank you!

2022-12-02 09:33 UTC, merged